name: flutter_lab_7
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0
  path: ^1.8.3
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.0
  google_maps_flutter: ^2.1.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  http: ^1.3.0
  dio: ^5.3.2
  retrofit: ^4.0.1
  shared_preferences: ^2.2.0
  mask_text_input_formatter: ^2.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  like_button: ^2.0.5
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_database: ^11.3.5
  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  sqflite_common_ffi: ^2.0.0
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true